#!/usr/bin/env ruby
# vim: ft=ruby

lib_path = "#{File.dirname(__FILE__)}/../lib"
if File.exist?(lib_path)
  $LOAD_PATH << lib_path
end

require 'warp/dir'
require 'warp/dir/app/cli'

Warp::Dir::App::CLI.new(ARGV.dup).run.tap do |response|
  response.print.exit! if response
end
